apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-appset-matrix
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - clusterDecisionResource:
              configMapRef: acm-placement
              labelSelector:
                matchLabels:
                  cluster.open-cluster-management.io/placement: argo-appset-matrix-placement
              requeueAfterSeconds: 180
          - git:
              repoURL: https://github.com/argoproj/argo-cd.git
              revision: HEAD
              directories:
                - path: applicationset/examples/matrix/cluster-addons/*
  template:
    metadata:
      name: argo-appset-matrix-{{name}}-{{path.basename}}
      annotations:
        apps.open-cluster-management.io/ocm-managed-cluster: "{{name}}"
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: openshift-gitops
        argocd.argoproj.io/skip-reconcile: "true"
      labels:
        velero.io/exclude-from-backup: "true"
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true"
    spec:
      project: default
      sources:
        - path: helloworld
          repoURL: https://github.com/fxiang1/app-samples
          targetRevision: main
      destination:
        namespace: "{{path.basename}}"
        server: "{{server}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: argo-appset-matrix-placement
  namespace: openshift-gitops
spec:
  numberOfClusters: 1
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: name
              operator: NotIn
              values:
                - local-cluster
  clusterSets:
    - auto-gitops-cluster-set
