apiVersion: v1
kind: Service
metadata:
  name: glauth-service
  namespace: qe-ldap
spec:
  selector:
    app: glauth
  ports:
    - name: ldap
      protocol: TCP
      port: 3893
      targetPort: ldap
