apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ansible-fake
  namespace: default
  labels:
    cluster.open-cluster-management.io/type: ans
    cluster.open-cluster-management.io/credentials: ""
stringData:
  host: https://ansible-tower-web-svc-tower-fake.apps.hivemind-b.aws.red-chesterfield.com
  token: fake-token
