apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app-test-cluster-manager-admin-clusterrolebinding
subjects:
- kind: User
  name: app-test-cluster-manager-admin
roleRef:
  kind: ClusterRole
  name: open-cluster-management:cluster-manager-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app-test-cluster-manager-admin-appset-clusterrolebinding
subjects:
- kind: User
  name: app-test-cluster-manager-admin
roleRef:
  kind: ClusterRole
  name: applicationsets.argoproj.io-v1alpha1-admin
  apiGroup: rbac.authorization.k8s.io  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app-test-cluster-manager-admin-gitops-clusterrolebinding
subjects:
- kind: User
  name: app-test-cluster-manager-admin
roleRef:
  kind: ClusterRole
  name: gitopsclusters.apps.open-cluster-management.io-v1alpha1-admin
  apiGroup: rbac.authorization.k8s.io    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app-test-cluster-manager-admin-ingress-clusterrolebinding
subjects:
- kind: User
  name: app-test-cluster-manager-admin
roleRef:
  kind: ClusterRole
  name: openshift-ingress-operator
  apiGroup: rbac.authorization.k8s.io  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app-test-cluster-admin-clusterrolebinding
subjects:
- kind: User
  name: app-test-cluster-admin
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-test-edit-clusterrolebinding
  namespace: default
subjects:
- kind: User
  name: app-test-edit
roleRef:
  kind: Role
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-test-admin-clusterrolebinding
  namespace: default
subjects:
- kind: User
  name: app-test-admin
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-test-view-clusterrolebinding
  namespace: default
subjects:
- kind: User
  name: app-test-view
roleRef:
  kind: Role
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: app-test-subscription-admin-clusterrolebinding
subjects:
- kind: User
  name: app-test-subscription-admin
roleRef:
  kind: ClusterRole
  name: open-cluster-management:subscription-admin
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: customresourcedefinition.apiextensions.k8s.io-view
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: customresourcedefinition.apiextensions.k8s.io-view
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: app-test-cluster-manager-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: customresourcedefinition.apiextensions.k8s.io-view
---
# Create openshift-gitops ns if it does not exist in interop tests
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-gitops
---
# AppSet Admin role: Full control
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: appset-admin
  namespace: openshift-gitops
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["applicationsets"]
    verbs: ["*"]
---
# AppSet Edit role: create and modify, but not delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: appset-edit
  namespace: openshift-gitops
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["applicationsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
# AppSet View role: read-only
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: appset-view
  namespace: openshift-gitops
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["applicationsets"]
    verbs: ["get", "list", "watch"]
---
# Bind appset-admin user
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bind-appset-admin
  namespace: openshift-gitops
subjects:
  - kind: User
    name: app-test-appset-admin
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: appset-admin
  apiGroup: rbac.authorization.k8s.io
---
# Bind appset-edit user
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bind-appset-edit
  namespace: openshift-gitops
subjects:
  - kind: User
    name: app-test-appset-edit
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: appset-edit
  apiGroup: rbac.authorization.k8s.io
---
# Bind appset-view user
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bind-appset-view
  namespace: openshift-gitops
subjects:
  - kind: User
    name: app-test-appset-view
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: appset-view
  apiGroup: rbac.authorization.k8s.io
