apiVersion: v1
kind: Namespace
metadata:
  name: {APP_NAMESPACE}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {APP_NAME}
  namespace: {APP_NAMESPACE}
spec:
  interval: 5m
  chart:
    spec:
      chart: {APP_CHART_NAME}
      version: '{APP_PACKAGE_VERSION}'
      sourceRef:
        kind: HelmRepository
        name: app-sample
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1