apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: app-samples
  namespace: flux-system
spec:
  timeout: 60s
  gitImplementation: go-git
  ref:
    branch: main
  interval: 5m
  url: "https://github.com/stolostron/application-lifecycle-samples.git"
