apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: to-automate-createcred-[ID]
  namespace: default
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.PT Protective Technology
    policy.open-cluster-management.io/controls: PR.PT-3 Least Functionality
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: to-automate-createcred-[ID]-nginx-pod
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Pod
                metadata:
                  name: nginx-pod-createcred-[ID]
                spec:
                  containers:
                    - image: nginx:1.18.0
                      name: nginx
                      ports:
                        - containerPort: 80
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-to-automate-createcred-[ID]
  namespace: default
placementRef:
  name: to-automate-createcred-[ID]-placement
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
  - name: to-automate-createcred-[ID]
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: to-automate-createcred-[ID]-placement
  namespace: default
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: local-cluster
              operator: In
              values:
                - 'true'
