apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: rhacm4k-32154-[ID]
  namespace: default
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rhacm4k-32154-[ID]
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Namespace
                apiVersion: v1
                metadata:
                  name: ns-32154
          pruneObjectBehavior: DeleteIfCreated
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: rhacm4k-32154-[ID]-placement
  namespace: default
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: feature.open-cluster-management.io/addon-config-policy-controller
              operator: In
              values:
                - 'available'
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: rhacm4k-32154-[ID]-pbinding
  namespace: default
placementRef:
  name: rhacm4k-32154-[ID]-placement
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
  - name: rhacm4k-32154-[ID]
    kind: Policy
    apiGroup: policy.open-cluster-management.io
