apiVersion: v1
kind: Namespace
metadata:
  name: compliance-test-ns
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: default
  namespace: compliance-test-ns
spec:
  clusterSet: default
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: compliance-check-placement
  namespace: compliance-test-ns
spec:
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
  clusterSets:
    - default
  numberOfClusters: 1
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: compliance-check-policy
  namespace: compliance-test-ns
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/controls: CM-6 Configuration Settings
spec:
  disabled: false
  remediationAction: inform
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: compliance-e8-scan
          labels:
            custom-classification: compliance-scan
        spec:
          remediationAction: inform
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: default
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: compliance-suite-e8
        spec:
          remediationAction: inform
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: default
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: compliance-check-placement-binding
  namespace: compliance-test-ns
placementRef:
  name: compliance-check-placement
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
subjects:
  - name: compliance-check-policy
    apiGroup: policy.open-cluster-management.io
    kind: Policy
