apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: test-[ID]-[TESTID]-e2e-rbac-test-1
  namespace: e2e-rbac-test-1
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  disabled: false
  remediationAction: inform
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: test-pod-policy-[ID]-[TESTID]-nginx-pod-rbac
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Pod
                metadata:
                  name: nginx-pod
                spec:
                  containers:
                    - name: nginx
                      image: nginx:1.18.0
                      ports:
                        - containerPort: 80
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: test-[ID]-[TESTID]-e2e-rbac-test-1-placement
  namespace: e2e-rbac-test-1
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: feature.open-cluster-management.io/addon-governance-policy-framework
              operator: In
              values:
                - available
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: test-[ID]-[TESTID]-e2e-rbac-test-1-placement
  namespace: e2e-rbac-test-1
placementRef:
  name: test-[ID]-[TESTID]-e2e-rbac-test-1-placement
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
  - name: test-[ID]-[TESTID]-e2e-rbac-test-1
    apiGroup: policy.open-cluster-management.io
    kind: Policy
