apiVersion: v1
kind: Namespace
metadata:
  name: git-placementrule
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: git-placementrule
  namespace: git-placementrule
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - git-placementrule
---
apiVersion: v1
kind: Namespace
metadata:
  name: ggithubcom-stolostron-application-lifecycle-samples-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: ggithubcom-stolostron-application-lifecycle-samples
  namespace: ggithubcom-stolostron-application-lifecycle-samples-ns
spec:
  type: Git
  pathname: 'https://github.com/stolostron/application-lifecycle-samples.git'
---
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  namespace: git-placementrule
  name: global
spec:
  clusterSet: global
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  labels:
    app: git-placementrule
  name: git-placementrule-placement-1
  namespace: git-placementrule
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: name
              operator: In
              values:
                - local-cluster
  clusterSets:
    - global
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: git-placementrule
  name: git-placementrule-placement-1
  namespace: git-placementrule
spec:
  clusterSelector:
    matchLabels:
      name: local-cluster
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: helloworld
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: git-placementrule
  name: git-placementrule-subscription-1
  namespace: git-placementrule
spec:
  channel: ggithubcom-stolostron-application-lifecycle-samples-ns/ggithubcom-stolostron-application-lifecycle-samples
  placement:
    placementRef:
      kind: PlacementRule
